# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b06d369261a689b3d2b6389bda3dbf31569e030360cecd6513c3788f4c0ab8fd1ec6a9a7b8fe1cfe72d41d60103f9e7482376e98457c96bd160f9e27b9e7740

test:
  secret_key_base: 5a37f388d3e16bf796c50657ab587aa474eefa8b2a361f39ead82ea5b77e4473740cedeb23bd7318cd675b76ac3095d16ac29ea78ac77d250f7ca85d2c17966e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
